#!/usr/bin/env node
import { writeFile, access } from "node:fs/promises";
import { resolve } from "node:path";
import { loadConfig, parseConfig } from "./config/loader.js";
import { buildGateway } from "./gateway/server.js";
import { parse as parseYaml } from "yaml";

const USAGE = `erouter — API gateway, resource aggregator & LLM router

Usage:
  erouter init [path]            write a starter erouter.yaml
  erouter validate <path>        parse and validate a config file
  erouter serve [--config <p>]   run the gateway (default: erouter.yaml)
  erouter --help                 show this help
  erouter --version              print version

LLM (when llm.enabled in yaml):
  GET  /v1/models
  POST /v1/chat/completions
  Point Cursor/Cline/Codex at http://HOST:PORT/v1
`;

const VERSION = "0.2.0";

function printUsage(): void {
  process.stdout.write(USAGE);
}

const STARTER = `# Generated by \`erouter init\`
server:
  host: 127.0.0.1
  port: 8080

auth:
  enabled: false
  header: x-api-key
  keys:
    - id: demo
      secret: change-me
      scopes: ["*"]
      rpm: 120
      burst: 30

rateLimit:
  enabled: true
  defaultRpm: 60
  defaultBurst: 30

cache:
  enabled: true
  defaultTtlMs: 30000
  maxEntries: 1000

routes:
  - id: hello
    match:
      path: /hello/:name
    upstream:
      url: https://api.github.com/users/{name}
    transform:
      pick: [login, id, name, bio]
    cache:
      ttlMs: 60000

  - id: book-search
    match:
      path: /books/:q
    aggregator:
      strategy: json-merge
      sources:
        - id: openlibrary
          url: https://openlibrary.org/search.json?q={q}
        - id: googlebooks
          url: https://www.googleapis.com/books/v1/volumes?q={q}
      merge:
        as: results
        pick:
          openlibrary: docs
          googlebooks: items
    transform:
      wrapAs: books

  - id: study-pool
    match:
      path: /pool/:key
    aggregator:
      strategy: pool
      poolKey: "{key}.json"

resources:
  pool:
    dir: ./data/pool
`;

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function cmdInit(target: string | undefined): Promise<number> {
  const out = resolve(target ?? "erouter.yaml");
  if (await exists(out)) {
    process.stderr.write(`refusing to overwrite existing file: ${out}\n`);
    return 1;
  }
  await writeFile(out, STARTER, "utf8");
  process.stdout.write(`wrote ${out}\n`);
  return 0;
}

async function cmdValidate(path: string): Promise<number> {
  const cfg = await loadConfig(path);
  process.stdout.write(`ok: ${cfg.routes.length} routes, server ${cfg.server.host}:${cfg.server.port}\n`);
  return 0;
}

async function cmdServe(configPath: string | undefined): Promise<number> {
  const cfgPath = configPath ?? resolve(process.cwd(), "erouter.yaml");
  const config = await loadConfig(cfgPath);
  const { app } = buildGateway({ config, logger: true });
  await app.listen({ host: config.server.host, port: config.server.port });
  process.stdout.write(`ERouter ${VERSION} listening on http://${config.server.host}:${config.server.port}\n`);
  return 0;
}

export async function runCli(argv: string[]): Promise<number> {
  const args = argv.slice(2);
  if (args.length === 0 || args[0] === "--help" || args[0] === "-h") {
    printUsage();
    return 0;
  }
  if (args[0] === "--version" || args[0] === "-v") {
    process.stdout.write(`${VERSION}\n`);
    return 0;
  }
  const cmd = args[0];
  if (cmd === "init") return cmdInit(args[1]);
  if (cmd === "validate") {
    if (!args[1]) {
      process.stderr.write("validate: missing config path\n");
      return 2;
    }
    return cmdValidate(args[1]!);
  }
  if (cmd === "serve") {
    const i = args.indexOf("--config");
    return cmdServe(i >= 0 ? args[i + 1] : undefined);
  }
  process.stderr.write(`unknown command: ${cmd}\n`);
    printUsage();
  return 2;
}

// re-export helpers for programmatic use
export { loadConfig, parseConfig, buildGateway, parseYaml };

// direct-invocation entrypoint
function isDirectInvocation(): boolean {
  if (!process.argv[1]) return false;
  const entry = process.argv[1].replace(/\\/g, "/");
  return entry.endsWith("/cli.js") || entry.endsWith("/dist/cli.js");
}

if (isDirectInvocation()) {
  runCli(process.argv).then(
    (code) => process.exit(code),
    (err) => {
      process.stderr.write(`erouter: ${err instanceof Error ? err.message : String(err)}\n`);
      process.exit(1);
    },
  );
}
